name: Deploy to GCP

env:
  REGION: asia-southeast1
  DOCKER_REGION: asia-southeast1-docker.pkg.dev
  IMAGE_NAME: zapchop-api
  ARTIFACT_PROJECT: zapchop-api
  CLOUD_RUN_SERVICE: zapchop-api

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Authenticate Docker
        run: gcloud auth configure-docker ${{ env.DOCKER_REGION }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_PROJECT }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_PROJECT }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
            --image ${{ env.DOCKER_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_PROJECT }}/${{ env.IMAGE_NAME }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated